packages:
  # all packages in direct subdirs of packages/
  - 'apps/*'
  - 'packages/*'
  - 'nodejs-assignments/*'
  # all packages in subdirs of nodejs-assignments/
  - 'course-resources/**'
  # exclude packages that are inside test directories
  - '!**/test/**'