packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of nodejs-assignments/
  - 'nodejs-assignments/*'
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'