packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'nodejs-assignments/*'
  - 'nodejs-assignments/assignment_002*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'